-- Full Seed Data Script
-- Run this as root to populate both AuthDB and ERPDB

-- ==========================================
-- AuthDB Setup
-- ==========================================
USE AuthDB;

-- Clear existing users (optional, be careful in production)
-- DELETE FROM users_auth WHERE username IN ('admin', 'student1', 'instructor1');

-- Insert Users with specific IDs to ensure consistency
-- Password 'admin123' hash: $2a$10$r.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ.zZ (Placeholder, using simple hash for demo if BCrypt not available in SQL, but app uses BCrypt)
-- We will use the hash for 'pass123' which is commonly used in testing: $2a$10$8yVzL.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x.0x (This is fake, I'll use a known hash or just let the app handle it. 
-- Actually, I'll insert with a known BCrypt hash for 'pass123' and 'admin123'.
-- 'pass123' -> $2a$10$EblZqNptyYpX.aOqTVvLZOwOQ2.3.4.5.6.7.8.9.0.1.2.3.4 (Fake valid format)
-- Let's use a real hash generated by the app previously or a standard one.
-- For this script, I will use a placeholder hash that I know works or just text if the app handles plain text (it doesn't, it uses BCrypt).
-- I will use a valid BCrypt hash for 'password': $2a$10$eAccYoNOHEqXve8aIWT8Nu3PkMXWBaFxJ9aOR.CpUEaypmQKG95LG

INSERT INTO users_auth (user_id, username, role, password_hash, status) VALUES 
(1000, 'admin', 'ADMIN', '$2a$10$eAccYoNOHEqXve8aIWT8Nu3PkMXWBaFxJ9aOR.CpUEaypmQKG95LG', 'ACTIVE'),
(1001, 'student1', 'STUDENT', '$2a$10$eAccYoNOHEqXve8aIWT8Nu3PkMXWBaFxJ9aOR.CpUEaypmQKG95LG', 'ACTIVE'),
(1002, 'instructor1', 'INSTRUCTOR', '$2a$10$eAccYoNOHEqXve8aIWT8Nu3PkMXWBaFxJ9aOR.CpUEaypmQKG95LG', 'ACTIVE')
ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash), role=VALUES(role);

-- ==========================================
-- ERPDB Setup
-- ==========================================
USE ERPDB;

-- 1. Instructors
INSERT IGNORE INTO instructors (user_id, department) VALUES 
(1002, 'Computer Science');

-- 2. Students
INSERT IGNORE INTO students (user_id, roll_no, program, year) VALUES 
(1001, 2025001, 'B.Sc. Computer Science', 1);

-- 3. Courses
INSERT IGNORE INTO courses (code, title, credits) VALUES 
('CS101', 'Intro to Programming', 4),
('CS102', 'Data Structures', 4),
('CS201', 'Database Systems', 3),
('MATH101', 'Calculus I', 3),
('ENG101', 'English Communication', 2);

-- 4. Sections
-- Instructor 1002 teaches CS101, CS102, CS201
INSERT INTO sections (section_id, course_id, instructor_id, day_time, room, capacity, semester, year, drop_deadline) VALUES 
(1, 'CS101', 1002, 'Mon/Wed 09:00-10:30', 'Room 301', 40, 1, 2025, '2025-12-31'),
(2, 'CS102', 1002, 'Tue/Thu 11:00-12:30', 'Room 302', 40, 1, 2025, '2025-12-31'),
(3, 'CS201', 1002, 'Fri 10:00-13:00', 'Lab 1', 30, 1, 2025, '2025-12-31'),
(4, 'MATH101', NULL, 'Mon/Wed 14:00-15:30', 'Room 201', 50, 1, 2025, '2025-12-31')
ON DUPLICATE KEY UPDATE instructor_id=VALUES(instructor_id), drop_deadline=VALUES(drop_deadline);

-- 5. Enrollments
-- Student 1001 enrolled in CS101 (Sec 1) and CS102 (Sec 2)
INSERT IGNORE INTO enrollments (enrollment_id, student_id, section_id, status) VALUES 
(1, 1001, 1, 'ENROLLED'),
(2, 1001, 2, 'ENROLLED');

-- 6. Grades
-- Grades for Enrollment 1 (CS101)
-- Components: 1=Midterm, 2=Final, 3=Project
INSERT INTO grades (enrollment_id, component, score, final_score) VALUES 
(1, 1, 85, NULL),
(1, 3, 90, NULL)
ON DUPLICATE KEY UPDATE score=VALUES(score);

-- 7. Fees
INSERT INTO fees (student_id, amount, description, due_date, status) VALUES 
(1001, 1500.00, 'Tuition Fee - Sem 1', '2025-09-01', 'PAID'),
(1001, 200.00, 'Lab Fee', '2025-09-15', 'PENDING');

-- 8. Attendance
-- Attendance for Enrollment 1
INSERT IGNORE INTO attendance (enrollment_id, date, status) VALUES 
(1, '2025-09-01', 'PRESENT'),
(1, '2025-09-03', 'PRESENT'),
(1, '2025-09-08', 'ABSENT');
